version: '3.8'

services:
  pco-arrivals-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pco-arrivals-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PCO_CLIENT_ID=${PCO_CLIENT_ID}
      - PCO_CLIENT_SECRET=${PCO_CLIENT_SECRET}
      - PCO_REDIRECT_URI=${PCO_REDIRECT_URI}
      - PCO_BASE_URL=${PCO_BASE_URL:-https://api.planningcenteronline.com}
      - PCO_SCOPES=${PCO_SCOPES:-people services check_ins}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - pco-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pco-arrivals-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pco-arrivals-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
      - VITE_WS_BASE_URL=${VITE_WS_BASE_URL:-ws://localhost:3000}
    depends_on:
      - pco-arrivals-backend
    networks:
      - pco-network

  nginx:
    image: nginx:alpine
    container_name: pco-arrivals-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - pco-arrivals-backend
      - pco-arrivals-frontend
    networks:
      - pco-network

networks:
  pco-network:
    driver: bridge

volumes:
  data:
  logs: 